#!/bin/bash
set -e
trap exit_cleanup EXIT
trap err_cleanup ERR

#export debug=$4
function exit_cleanup() {
	[ $? -gt 0 ] || rm -r "$uploadDir" #&>> $REPOROOT/error_log_$(date +%Y%m%d)
	exit
}

function err_cleanup() {
#	[ ${StudyImageID:-0} -gt 0 ] && echo "$origDICOM" >> $REPOROOT/PROBLEM_WITH_$StudyImageID
#	[ ${StudyImageID:-0} -eq 0 ] && echo "$origDICOM $FileSetID" >> $REPOROOT/PROBLEM_WITH_0_RAWDICOM
	[ ${StudyImageID:-0} -gt 0 ] && echo "$origDICOM" | gfput --append glfs://painrepo/gv0/logs/PROBLEM_WITH_$StudyImageID
	[ ${StudyImageID:-0} -eq 0 ] && echo "$origDICOM $FileSetID" | gfput --append glfs://painrepo/gv0/logs/PROBLEM_WITH_0_RAWDICOM
	exit 1
}

export LC_ALL=C
export PATH=/mnt/data/imaging/dcmtk/bin:$PATH
export DCMDICTPATH=/mnt/data/imaging/dcmtk/share/dcmtk/dicom.dic:/mnt/data/imaging/dcmtk/share/dcmtk/private.dic
export REPOROOT=/mnt/gluster/gv0/data
#export REPOROOT=glfs://painrepo/gv0/data
export TEMPDIR=/dev/shm/upload

declare -a REMOVE_DICOM_FIELDS=(
	0010,0030
	0010,0040
	0010,1020
	0010,1030
)

while getopts "u:f:s:m:o" opt
do
 case $opt in
  u) uploadID="$OPTARG";;
  f) origDICOM="$OPTARG";;
  s) newPatientID=$OPTARG;;
  m) DCM_MODIFICATION="$OPTARG";;
  o) OVERWRITE=1;;
 esac
done


#	uploadID=$1
#	origDICOM="$2"
#	newPatientID="$3"
#	[ $# -eq 4 -a ${#4} -gt 0 ] && DCM_MODIFICATION="$4"
	[ $uploadID -ge 0 ] && [[ $(file -b "$origDICOM") =~ DICOM\ medical\ imaging\ data ]] || exit

	FileSetID=$(dcm 4 1130 "$origDICOM" 2>&1) && [ "${FileSetID:-X}" != X ] && err_cleanup
	ImageType=$(dcm 8    8 "$origDICOM") && [[ $ImageType =~ CSA\ REPORT ]] && exit_cleanup

	uploadDir=$(mktemp --directory --tmpdir=$TEMPDIR)
	cp --sparse=always --dereference -p "$origDICOM" $uploadDir/
	uploadFile=$uploadDir/${origDICOM##*/}

	# Modification of PatientID & PatientName
	if [[ $DCM_MODIFICATION =~ \([0-9]{4},[0-9a-f]{4}\)\=.+ ]]; then
		dcmodify -nb --ignore-missing-tags  -m "(0010,0010)=$newPatientID" -m "(0010,0020)=$newPatientID" -m "$DCM_MODIFICATION"  $(for f in ${REMOVE_DICOM_FIELDS[@]}; do printf ' -e (%s) ' $f; done)  "$uploadFile"
	elif [[ ${#newPatientID} -gt 0 ]]; then
		dcmodify -nb --ignore-missing-tags  -m "(0010,0010)=$newPatientID" -m "(0010,0020)=$newPatientID"  $(for f in ${REMOVE_DICOM_FIELDS[@]}; do printf ' -e (%s) ' $f; done)  "$uploadFile"
	fi	
	uploadMD5=($(md5sum $uploadFile))

	if [ "$(dcm 8 70 $uploadFile)" == "Philips Medical Systems" ]; then
		dcm2xml "$uploadFile" | xsltproc /mnt/data/DICOM/SCRIPTS/required_set.xsl - > "${uploadFile}.xml"
	else
		dcm2xml "$uploadFile" "${uploadFile}.xml"
	fi

	chmod -R 777 $uploadDir

#	if [ ${uploadID:-0} -eq 0 ]; then
#		sql=$(printf 'SELECT getUploadIDHeuristic(\047%s\047);' "$(dcm 8 1030 $uploadFile)")
#		uploadID=$(mysql --silent --silent --raw -uroot  Quarantine -e "$sql")
#		[ $uploadID -le 0 ] && exit
#	fi

	sql=$(printf 'CALL proc_load(\047%s\047,\047%s\047,\047%s\047,%d,%i);' "${origDICOM}" $uploadMD5 "${uploadFile}.xml" $uploadID ${OVERWRITE:-0})

	read -a sql_results <<<$(mysql  --silent --silent --max_allowed_packet=2G --raw -uroot  Quarantine -e "$sql")
	StudyImageID=${sql_results[0]}

	if [[ ${StudyImageID:-X} =~ [^0-9] || ${StudyImageID} -le 0 ]]; then
		printf "0:%s:%s:NULL\n" $StudyImageID "$origDICOM"
		exit
	fi
	ScanSessionID=${sql_results[1]}

	SeriesNumber=$(dcm 20 11 "$uploadFile")
	AcquisitionNumber=$(dcm 20 12 "$uploadFile")
	InstanceNumber=$(dcm 20 13 "$uploadFile")
	[ ${SeriesNumber:-0} -le 0 ] && echo "Invalid Series Number: $origDICOM" && err_cleanup
	[ ${AcquisitionNumber:-0} -le 0 ] && echo "Invalid Acquisition Number ($AcquisitionNumber): $origDICOM" && err_cleanup
	[ ${InstanceNumber:-0} -le 0 ] && echo "Invalid Instance Number: $origDICOM" && err_cleanup

#	[ -d $REPOROOT/RAWDATA/$StudyImageID ] || mkdir -p $REPOROOT/{RAWDATA,XML}/$StudyImageID
#	[ -d $REPOROOT/XML/$StudyImageID ] || mkdir -p $REPOROOT/{RAWDATA,XML}/$StudyImageID
#	gfmkdir $REPOROOT/RAWDATA/$StudyImageID && gfmkdir $REPOROOT/XML/$StudyImageID
	mkdir -p $REPOROOT/{RAWDATA,XML}/$StudyImageID
	if [ ${#newPatientID} -gt 0 ]; then
		newDICOM=$REPOROOT/RAWDATA/$StudyImageID/$(printf "%s_ser%02d_acq%02d_img%05d.dcm" "$newPatientID" $SeriesNumber $AcquisitionNumber $InstanceNumber)
		cp -p "$uploadFile" "$newDICOM"
		cp -p "${uploadFile}.xml" $REPOROOT/XML/$StudyImageID/$(printf "%05d".xml $InstanceNumber)
		#gfcp "$uploadFile" "$newDICOM"
		#gfcp "${uploadFile}.xml" $REPOROOT/XML/$StudyImageID/$(printf "%05d".xml $InstanceNumber)
	else
		newDICOM="$REPOROOT/RAWDATA/$StudyImageID/${uploadFile##*/}"
		cp -p "$uploadFile" $REPOROOT/RAWDATA/$StudyImageID/
		cp -p "${uploadFile}.xml" $REPOROOT/XML/$StudyImageID/$(printf "%05d".xml $InstanceNumber)
		#gfcp "$uploadFile" $REPOROOT/RAWDATA/$StudyImageID/
		#gfcp "${uploadFile}.xml" $REPOROOT/XML/$StudyImageID/$(printf "%05d".xml $InstanceNumber)
	fi

	touch -m --reference="$origDICOM" "$newDICOM"
	newMD5=($(md5sum "$newDICOM"))
	[ ${newMD5:-foobar} != $uploadMD5 ] && printf "Error in file %s part of StudyImage %d\n" "$origDICOM" $StudyImageID && err_cleanup
	printf "%s:%s:%s:%s\n" ${ScanSessionID:-0} $StudyImageID "$origDICOM" "$newDICOM"

